(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "Date_internal" "*external*" with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Date_internal, it may need recompiling"
module Date_internal = Date_internal
let () =
  match Catala_runtime.check_module "List_en" "CM0|30c623e2|32e49b03|2f449d20"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module List_en, it may need recompiling"
module List_en = List_en

module Month = struct
  type t =
    | January
    | February
    | March
    | April
    | May
    | June
    | July
    | August
    | September
    | October
    | November
    | December
  let rtype = Value.Enum {
    name = "Month";
    constr = function
      | January -> 0, "January", None
      | February -> 1, "February", None
      | March -> 2, "March", None
      | April -> 3, "April", None
      | May -> 4, "May", None
      | June -> 5, "June", None
      | July -> 6, "July", None
      | August -> 7, "August", None
      | September -> 8, "September", None
      | October -> 9, "October", None
      | November -> 10, "November", None
      | December -> 11, "December", None
  }
end

module Day_of_week = struct
  type t =
    | Monday
    | Tuesday
    | Wednesday
    | Thursday
    | Friday
    | Saturday
    | Sunday
  let rtype = Value.Enum {
    name = "Day_of_week";
    constr = function
      | Monday -> 0, "Monday", None
      | Tuesday -> 1, "Tuesday", None
      | Wednesday -> 2, "Wednesday", None
      | Thursday -> 3, "Thursday", None
      | Friday -> 4, "Friday", None
      | Saturday -> 5, "Saturday", None
      | Sunday -> 6, "Sunday", None
  }
end


(* Toplevel def loc *)
let loc : code_location array =
  [|{filename="libcatala/date_en.catala_en"; start_line=134; start_column=5;
     end_line=134; end_column=22;
     law_headings=["Getting to the past or future"; "Dates"]};
    {filename="libcatala/date_en.catala_en"; start_line=151; start_column=5;
     end_line=151; end_column=22;
     law_headings=["Getting to the past or future"; "Dates"]};
    {filename="libcatala/date_en.catala_en"; start_line=160; start_column=5;
     end_line=160; end_column=22;
     law_headings=["Getting to the past or future"; "Dates"]};
    {filename="libcatala/date_en.catala_en"; start_line=220; start_column=60;
     end_line=220; end_column=70; law_headings=["Named months"; "Dates"]};
    {filename="libcatala/date_en.catala_en"; start_line=333; start_column=16;
     end_line=333; end_column=26;
     law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                    "Dates"]};
    {filename="libcatala/date_en.catala_en"; start_line=337; start_column=19;
     end_line=337; end_column=36;
     law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                    "Dates"]};
    {filename="libcatala/date_en.catala_en"; start_line=338; start_column=19;
     end_line=338; end_column=38;
     law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                    "Dates"]};
    {filename="libcatala/date_en.catala_en"; start_line=339; start_column=19;
     end_line=339; end_column=38;
     law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                    "Dates"]};
    {filename="libcatala/date_en.catala_en"; start_line=342; start_column=22;
     end_line=350; end_column=6;
     law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                    "Dates"]};
    {filename="libcatala/date_en.catala_en"; start_line=344; start_column=21;
     end_line=344; end_column=38;
     law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                    "Dates"]};
    {filename="libcatala/date_en.catala_en"; start_line=345; start_column=21;
     end_line=345; end_column=40;
     law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                    "Dates"]};
    {filename="libcatala/date_en.catala_en"; start_line=346; start_column=21;
     end_line=346; end_column=40;
     law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                    "Dates"]};
    {filename="libcatala/date_en.catala_en"; start_line=354; start_column=14;
     end_line=354; end_column=24;
     law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                    "Dates"]}|]

(* Toplevel def min *)
let min : date -> date -> date =
  fun (d1: date) (d2: date) -> if d1 <= d2 then d1 else d2

(* Toplevel def max *)
let max : date -> date -> date =
  fun (d1: date) (d2: date) -> if d1 >= d2 then d1 else d2

(* Toplevel def add_round_down *)
let add_round_down : date -> duration -> date =
  fun (t: date) (dt: duration) -> (Date_internal.add_rounded_down) t dt

(* Toplevel def add_round_up *)
let add_round_up : date -> duration -> date =
  fun (t: date) (dt: duration) -> (Date_internal.add_rounded_up) t dt

(* Toplevel def sub_round_down *)
let sub_round_down : date -> duration -> date =
  fun (t: date) (dt: duration) ->
    (Date_internal.add_rounded_down) t (o_minus_dur dt)

(* Toplevel def sub_round_up *)
let sub_round_up : date -> duration -> date =
  fun (t: date) (dt: duration) ->
    (Date_internal.add_rounded_up) t (o_minus_dur dt)

(* Toplevel def of_year_month_day *)
let of_year_month_day : code_location -> integer -> integer -> integer ->
                          date =
  fun (pos: code_location) (dyear: integer) (dmonth: integer)
    (dday: integer) -> (Date_internal.of_ymd) pos dyear dmonth dday

(* Toplevel def to_year_month_day *)
let to_year_month_day : date -> (integer * integer * integer) =
  fun (d: date) -> (Date_internal.to_ymd) d

(* Toplevel def get_year *)
let get_year : date -> integer =
  fun (d: date) -> let x, _, _ = (to_year_month_day d) in x

(* Toplevel def get_month *)
let get_month : date -> integer =
  fun (d: date) -> let _, x, _ = (to_year_month_day d) in x

(* Toplevel def get_day *)
let get_day : date -> integer =
  fun (d: date) -> let _, _, x = (to_year_month_day d) in x

(* Toplevel def first_day_of_month *)
let first_day_of_month : date -> date =
  fun (d: date) ->
    let ymd : (integer * integer * integer) = (to_year_month_day d) in
    of_year_month_day (loc.(0)) (let x, _, _ = ymd in x)
      (let _, x, _ = ymd in x) (integer_of_int 1)

(* Toplevel def last_day_of_month *)
let last_day_of_month : date -> date =
  fun (d: date) -> (Date_internal.last_day_of_month) d

(* Toplevel def first_day_of_year *)
let first_day_of_year : date -> date =
  fun (d: date) ->
    let ymd : (integer * integer * integer) = (to_year_month_day d) in
    of_year_month_day (loc.(1)) (let x, _, _ = ymd in x) (integer_of_int 1)
      (integer_of_int 1)

(* Toplevel def last_day_of_year *)
let last_day_of_year : date -> date =
  fun (d: date) ->
    let ymd : (integer * integer * integer) = (to_year_month_day d) in
    of_year_month_day (loc.(2)) (let x, _, _ = ymd in x) (integer_of_int 12)
      (integer_of_int 31)

(* Toplevel def month_to_integer *)
let month_to_integer : Month.t -> integer =
  fun (m: Month.t) ->
    match m with
    | Month.January -> (integer_of_int 1)
    | Month.February -> (integer_of_int 2)
    | Month.March -> (integer_of_int 3)
    | Month.April -> (integer_of_int 4)
    | Month.May -> (integer_of_int 5)
    | Month.June -> (integer_of_int 6)
    | Month.July -> (integer_of_int 7)
    | Month.August -> (integer_of_int 8)
    | Month.September -> (integer_of_int 9)
    | Month.October -> (integer_of_int 10)
    | Month.November -> (integer_of_int 11)
    | Month.December -> (integer_of_int 12)

(* Toplevel def integer_to_month *)
let integer_to_month : code_location -> integer -> Month.t =
  fun (pos: code_location) (i: integer) ->
    if i = (integer_of_int 1)
    then Month.January
    else if i = (integer_of_int 2)
    then Month.February
    else if i = (integer_of_int 3)
    then Month.March
    else if i = (integer_of_int 4)
    then Month.April
    else if i = (integer_of_int 5)
    then Month.May
    else if i = (integer_of_int 6)
    then Month.June
    else if i = (integer_of_int 7)
    then Month.July
    else if i = (integer_of_int 8)
    then Month.August
    else if i = (integer_of_int 9)
    then Month.September
    else if i = (integer_of_int 10)
    then Month.October
    else if i = (integer_of_int 11)
    then Month.November
    else if i = (integer_of_int 12)
    then Month.December
    else
      (let _ : date =
         ((Date_internal.of_ymd) pos (integer_of_int (-1))
            (integer_of_int (-1)) (integer_of_int (-1)))
       in
       raise
       (Error (Impossible, [loc.(3)], None)))

(* Toplevel def is_old_enough_rounding_down *)
let is_old_enough_rounding_down : date -> duration -> date -> bool =
  fun (birth_date: date) (age: duration) (at_date: date) ->
    at_date >= ((Date_internal.add_rounded_down) birth_date age)

(* Toplevel def is_old_enough_rounding_up *)
let is_old_enough_rounding_up : date -> duration -> date -> bool =
  fun (birth_date: date) (age: duration) (at_date: date) ->
    at_date >= ((Date_internal.add_rounded_up) birth_date age)

(* Toplevel def is_young_enough_rounding_down *)
let is_young_enough_rounding_down : date -> duration -> date -> bool =
  fun (birth_date: date) (age: duration) (at_date: date) ->
    o_not (is_old_enough_rounding_down birth_date age at_date)

(* Toplevel def is_young_enough_rounding_up *)
let is_young_enough_rounding_up : date -> duration -> date -> bool =
  fun (birth_date: date) (age: duration) (at_date: date) ->
    o_not (is_old_enough_rounding_up birth_date age at_date)

(* Toplevel def day_of_week *)
let day_of_week : date -> Day_of_week.t =
  fun (given_date: date) ->
    let month_number : integer = (get_month given_date) in
    let year_number : integer =
      (if month_number < (integer_of_int 3)
       then (o_sub_int_int (get_year given_date) (integer_of_int 1))
       else (get_year given_date))
    in
    let n_number : integer =
      (match
         ((List_en.nth_element)
            ([|(integer_of_int 0); (integer_of_int 3); (integer_of_int 2);
               (integer_of_int 5); (integer_of_int 0); (integer_of_int 3);
               (integer_of_int 5); (integer_of_int 1); (integer_of_int 4);
               (integer_of_int 6); (integer_of_int 2); (integer_of_int 4)|])
            month_number)
       with
       | Optional.Absent -> (raise (Error (Impossible, [loc.(4)], None)))
       | Optional.Present n -> n)
    in
    let day_number : integer =
      (o_sub_int_int
         (o_add_int_int
            (o_add_int_int
               (o_add_int_int
                  (o_sub_int_int
                     (o_add_int_int year_number
                        (o_toint_rat
                           (o_div_int_int (loc.(5)) year_number
                              (integer_of_int 4))))
                     (o_toint_rat
                        (o_div_int_int (loc.(6)) year_number
                           (integer_of_int 100))))
                  (o_toint_rat
                     (o_div_int_int (loc.(7)) year_number
                        (integer_of_int 400)))) n_number)
            (get_day given_date))
         (o_mult_int_int (integer_of_int 7)
            (o_toint_rat
               (o_div_int_int (loc.(8))
                  (o_add_int_int
                     (o_add_int_int
                        (o_add_int_int
                           (o_sub_int_int
                              (o_add_int_int year_number
                                 (o_toint_rat
                                    (o_div_int_int (loc.(9)) year_number
                                       (integer_of_int 4))))
                              (o_toint_rat
                                 (o_div_int_int (loc.(10)) year_number
                                    (integer_of_int 100))))
                           (o_toint_rat
                              (o_div_int_int (loc.(11)) year_number
                                 (integer_of_int 400)))) n_number)
                     (get_day given_date)) (integer_of_int 7)))))
    in
    match
      ((List_en.nth_element)
         ([|Day_of_week.Sunday; Day_of_week.Monday; Day_of_week.Tuesday;
            Day_of_week.Wednesday; Day_of_week.Thursday; Day_of_week.Friday;
            Day_of_week.Saturday|])
         (o_add_int_int day_number (integer_of_int 1)))
    with
    | Optional.Absent -> (raise (Error (Impossible, [loc.(12)], None)))
    | Optional.Present d -> d

let () =
  Catala_runtime.register_module "Date_en"
    [ "min", Stdlib.Obj.repr (min);
      "max", Stdlib.Obj.repr (max);
      "add_round_down", Stdlib.Obj.repr (add_round_down);
      "add_round_up", Stdlib.Obj.repr (add_round_up);
      "sub_round_down", Stdlib.Obj.repr (sub_round_down);
      "sub_round_up", Stdlib.Obj.repr (sub_round_up);
      "of_year_month_day", Stdlib.Obj.repr (of_year_month_day);
      "to_year_month_day", Stdlib.Obj.repr (to_year_month_day);
      "get_year", Stdlib.Obj.repr (get_year);
      "get_month", Stdlib.Obj.repr (get_month);
      "get_day", Stdlib.Obj.repr (get_day);
      "first_day_of_month", Stdlib.Obj.repr (first_day_of_month);
      "last_day_of_month", Stdlib.Obj.repr (last_day_of_month);
      "first_day_of_year", Stdlib.Obj.repr (first_day_of_year);
      "last_day_of_year", Stdlib.Obj.repr (last_day_of_year);
      "month_to_integer", Stdlib.Obj.repr (month_to_integer);
      "integer_to_month", Stdlib.Obj.repr (integer_to_month);
      "is_old_enough_rounding_down",
        Stdlib.Obj.repr (is_old_enough_rounding_down);
      "is_old_enough_rounding_up",
        Stdlib.Obj.repr (is_old_enough_rounding_up);
      "is_young_enough_rounding_down",
        Stdlib.Obj.repr (is_young_enough_rounding_down);
      "is_young_enough_rounding_up",
        Stdlib.Obj.repr (is_young_enough_rounding_up);
      "day_of_week", Stdlib.Obj.repr (day_of_week) ]
    "CM0|30c623e2|32e49b03|38c17cb3"
