(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "Decimal_internal" "*external*" with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Decimal_internal, it may need recompiling"
module Decimal_internal = Decimal_internal


(* Toplevel def loc *)
let loc : code_location array =
  [|{filename="libcatala/decimal_en.catala_en";
     start_line=17; start_column=8; end_line=17; end_column=15;
     law_headings=["Helper functions"; "Decimals"]};
    {filename="libcatala/decimal_en.catala_en";
     start_line=26; start_column=8; end_line=26; end_column=15;
     law_headings=["Helper functions"; "Decimals"]};
    {filename="libcatala/decimal_en.catala_en";
     start_line=64; start_column=13; end_line=64; end_column=20;
     law_headings=["Helper functions"; "Decimals"]};
    {filename="libcatala/decimal_en.catala_en";
     start_line=77; start_column=8; end_line=77; end_column=16;
     law_headings=["Helper functions"; "Decimals"]};
    {filename="libcatala/decimal_en.catala_en";
     start_line=92; start_column=8; end_line=92; end_column=15;
     law_headings=["Helper functions"; "Decimals"]}|]

(* Toplevel def min *)
let min : decimal -> decimal -> decimal =
  fun (d1: decimal) (d2: decimal) ->
    if o_gt (Value.Decimal) (loc.(0)) d1 d2 then d2 else d1

(* Toplevel def max *)
let max : decimal -> decimal -> decimal =
  fun (d1: decimal) (d2: decimal) ->
    if o_gt (Value.Decimal) (loc.(1)) d1 d2 then d1 else d2

(* Toplevel def ceiling *)
let ceiling : decimal -> decimal -> decimal =
  fun (d: decimal) (max_value: decimal) -> min d max_value

(* Toplevel def floor *)
let floor : decimal -> decimal -> decimal =
  fun (d: decimal) (min_value: decimal) -> max d min_value

(* Toplevel def positive *)
let positive : decimal -> decimal =
  fun (d: decimal) -> floor d (Q.of_int 0)

(* Toplevel def truncate *)
let truncate : decimal -> decimal =
  fun (d: decimal) ->
    if d = (Q.of_int 0)
    then (Q.of_int 0)
    else if o_gt (Value.Decimal) (loc.(2)) d (Q.of_int 0)
    then
      (o_round_rat
         (o_sub_rat_rat d ({ Q.num = Z.of_int 1; den = Z.of_int 2 })))
    else
      (o_round_rat
         (o_add_rat_rat d ({ Q.num = Z.of_int 1; den = Z.of_int 2 })))

(* Toplevel def round_by_excess *)
let round_by_excess : decimal -> decimal =
  fun (d: decimal) ->
    if o_gte (Value.Decimal) (loc.(3)) d (Q.of_int 0)
    then
      (if (truncate d) = d
       then d
       else (truncate (o_add_rat_rat d (Q.of_int 1))))
    else
      (o_round_rat
         (o_add_rat_rat d ({ Q.num = Z.of_int 1; den = Z.of_int 2 })))

(* Toplevel def round_by_default *)
let round_by_default : decimal -> decimal =
  fun (d: decimal) ->
    if o_gt (Value.Decimal) (loc.(4)) d (Q.of_int 0)
    then (truncate d)
    else if (truncate d) = d
    then d
    else (truncate (o_sub_rat_rat d (Q.of_int 1)))

(* Toplevel def round_to_decimal *)
let round_to_decimal : decimal -> integer -> decimal =
  fun (d: decimal) (nth_decimal: integer) ->
    (Decimal_internal.round_to_decimal) d nth_decimal

(* Toplevel def sum *)
let sum : (decimal array) -> decimal =
  fun (l: decimal array) ->
    o_fold (fun (total: decimal) (x: decimal) -> o_add_rat_rat total x)
      (Q.of_int 0) l

let () =
  Catala_runtime.register_module "Decimal_en"
    [ "min", Stdlib.Obj.repr (min);
      "max", Stdlib.Obj.repr (max);
      "ceiling", Stdlib.Obj.repr (ceiling);
      "floor", Stdlib.Obj.repr (floor);
      "positive", Stdlib.Obj.repr (positive);
      "truncate", Stdlib.Obj.repr (truncate);
      "round_by_excess", Stdlib.Obj.repr (round_by_excess);
      "round_by_default", Stdlib.Obj.repr (round_by_default);
      "round_to_decimal", Stdlib.Obj.repr (round_to_decimal);
      "sum", Stdlib.Obj.repr (sum) ]
    "CM0|30c623e2|32e49b03|34d55d74"
