(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime



(* Toplevel def loc *)
let loc : code_location array =
  [|{filename="libcatala/duration_en.catala_en";
     start_line=17; start_column=8; end_line=17; end_column=17;
     law_headings=["Helper functions"; "Durations"]}|]

(* Toplevel def positive *)
let positive : duration -> duration =
  fun (d: duration) ->
    if o_gt (Value.Duration) (loc.(0)) d (duration_of_numbers 0 0 0)
    then d
    else (duration_of_numbers 0 0 0)

(* Toplevel def sum *)
let sum : (duration array) -> duration =
  fun (l: duration array) ->
    o_fold (fun (total: duration) (x: duration) -> o_add_dur_dur total x)
      (duration_of_numbers 0 0 0) l

let () =
  Catala_runtime.register_module "Duration_en"
    [ "positive", Stdlib.Obj.repr (positive);
      "sum", Stdlib.Obj.repr (sum) ]
    "CM0|30c623e2|32e49b03|25986afc"
