(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "Date_en" "CM0|30c623e2|32e49b03|38c17cb3"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Date_en, it may need recompiling"
module Date_en = Date_en
let () =
  match Catala_runtime.check_module "List_en" "CM0|30c623e2|32e49b03|2f449d20"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module List_en, it may need recompiling"
module List_en = List_en
let () =
  match Catala_runtime.check_module "Duration_en" "CM0|30c623e2|32e49b03|25986afc"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Duration_en, it may need recompiling"
module Duration_en = Duration_en
let () =
  match Catala_runtime.check_module "MonthYear_en" "CM0|30c623e2|32e49b03|28c18d12"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module MonthYear_en, it may need recompiling"
module MonthYear_en = MonthYear_en
let () =
  match Catala_runtime.check_module "Period_en" "CM0|30c623e2|32e49b03|02eca492"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Period_en, it may need recompiling"
module Period_en = Period_en
let () =
  match Catala_runtime.check_module "Money_en" "CM0|30c623e2|32e49b03|3f4804db"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Money_en, it may need recompiling"
module Money_en = Money_en
let () =
  match Catala_runtime.check_module "Integer_en" "CM0|30c623e2|32e49b03|361feb9d"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Integer_en, it may need recompiling"
module Integer_en = Integer_en
let () =
  match Catala_runtime.check_module "Decimal_en" "CM0|30c623e2|32e49b03|34d55d74"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Decimal_en, it may need recompiling"
module Decimal_en = Decimal_en


let () =
  Catala_runtime.register_module "Stdlib_en"
    [  ]
    "CM0|30c623e2|32e49b03|165aeded"
